# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from statik import recource_qr
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 477)
        Form.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: #46494C")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(5, 0, 5, 5)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_widget = QtWidgets.QWidget(self.widget)
        self.search_widget.setMinimumSize(QtCore.QSize(0, 60))
        self.search_widget.setStyleSheet("#search_widget{\n"
"    background-color:#ABB2B9;\n"
"}\n"
"#search_widget {\n"
"    border: 0px solid #110B11;\n"
"    border-radius:30px;\n"
"    background-color:#46494C\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout_2.setContentsMargins(15, 0, 15, 15)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_frame = QtWidgets.QFrame(self.search_widget)
        self.search_frame.setMinimumSize(QtCore.QSize(900, 30))
        self.search_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.search_frame.setStyleSheet("#search_frame {\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:#4C5C68;\n"
"}\n"
"\n"
"#search_frame QPushButton {\n"
"    padding: 5px 5px;\n"
"    border-radius:15 px;\n"
"}\n"
"\n"
"#search_frame QPushButton:pressed {\n"
"    padding-left:  1 px;\n"
"}\n"
"\n"
"")
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.search_frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(800, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: none;\n"
"background-color:#4C5C68;\n"
"\n"
"color: #DCDCDD;")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_9 = QtWidgets.QPushButton(self.search_frame)
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
"    background-color: rgb(28, 154, 185);\n"
"    \n"
"    border-radius: 15%;\n"
"}\n"
"")
        self.pushButton_9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.horizontalLayout_2.addWidget(self.search_frame)
        spacerItem1 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.search_widget, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("#textEdit{\n"
"    border-radius: 0px; \n"
"    color: #DCDCDD;\n"
"    background-color: #46494C;\n"
"    border: 0px\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter command"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
